# Generated by Django 4.0.6 on 2022-12-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0003_article_create_date_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_article',
            field=models.BooleanField(default=True, verbose_name='مقاله میباشد'),
        ),
    ]
