# Generated by Django 4.0.6 on 2022-12-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0006_article_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_learning',
            field=models.BooleanField(default=False, verbose_name='مقاله از نوع ترفند میباشد / نمیباشد'),
        ),
    ]
