# Generated by Django 4.0.6 on 2022-12-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0008_remove_article_is_learning'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_suggest',
            field=models.BooleanField(default=False, verbose_name='پیشنهاد سردبیر'),
        ),
    ]
