# Generated by Django 4.0.6 on 2022-12-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0009_article_is_suggest'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_slider',
            field=models.BooleanField(default=False, verbose_name='نمایش در اسلایدر'),
        ),
    ]
